#ifndef MKINTERFACES_GLOBAL_H
#define MKINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MKINTERFACES_LIBRARY)
#  define MKINTERFACESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MKINTERFACESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MKINTERFACES_GLOBAL_H
