#ifndef PDINTERFACES_GLOBAL_H
#define PDINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PDINTERFACES_LIBRARY)
#  define PDINTERFACESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PDINTERFACESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PDINTERFACES_GLOBAL_H
